name       : xalan-c
version    : 1.12
release    : 1
source     :
    - https://downloads.apache.org/xalan/xalan-c/sources/xalan_c-1.12.tar.gz : ee7d4b0b08c5676f5e586c7154d94a5b32b299ac3cbb946e24c4375a25552da7
homepage   : https://xalan.apache.org/
license    : Apache-2.0
component  : programming
summary    : A XSLT processor for transforming XML documents
description: |
    The Apache Xalan-C++ Project provides a library and a command line program to transform XML documents using a stylesheet that conforms to XSLT 1.0 standards.
builddeps  :
    - pkgconfig(xerces-c)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
